// Compose the full newsletter-001 video by concatenating the per-clip mp4s in
// cut-list order. Run from anywhere: `bun content/newsletter-001/compose.ts`.
//
// Clips are produced independently (each clips/<name>/<name>.mp4) at varying
// framerates (screencast clips are ~25fps, stills clips 30fps), so a plain
// concat-demuxer stream-copy is unsafe. We re-encode through the concat filter,
// normalizing every input to 1280×720 @ 30fps, square pixels, H.264.

import { existsSync } from 'node:fs';
import { join } from 'node:path';
import { spawnSync } from 'node:child_process';

const SERIES_DIR = import.meta.dir;
const CLIPS_DIR = join(SERIES_DIR, 'clips');

// Canonical order from script.txt. Missing clips (not yet shot) are skipped,
// so the rough cut grows as clips land. Edit this list to re-order or drop a
// clip (e.g. comment out 'parametric-svg' while its drag is still parked).
const ORDER = [
  'intro',
  'cmd-k', // moved up: opens with the palette before the hook
  'parametric-svg', // hook
  'pairing',
  'exporter',
  'file-sync',
  // 'history', // skipped: 18.9s outlier, dropped from the cut
  'themes',
  'lsp',
  'drag-out',
  'pdf-tab',
  'atproto',
  'linux',
  'end-card',
  'outro', // reverse of intro: prints completion + link, ejects the disk; loops back to the intro
];

const FPS = 30;
const W = 1280;
const H = 720;

// A clip may have a hand-finished cut `<name>-final.mp4` (trimmed/tweaked in
// an editor) that supersedes the raw `<name>.mp4` capture. Prefer it.
const resolveClip = (name: string): string | null => {
  const final = join(CLIPS_DIR, name, `${name}-final.mp4`);
  if (existsSync(final)) return final;
  const raw = join(CLIPS_DIR, name, `${name}.mp4`);
  if (existsSync(raw)) return raw;
  return null;
};

// A feature clip is preceded by its title card if one was generated by
// make-titles.ts (.titles/<name>.mp4). Cards announce the feature + module.
const TITLES_DIR = join(SERIES_DIR, '.titles');
const titleCard = (name: string): string | null => {
  const card = join(TITLES_DIR, `${name}.mp4`);
  return existsSync(card) ? card : null;
};

// Flatten ORDER into the actual segment sequence: [card?] clip [card?] clip …
const clips: { name: string; path: string }[] = [];
for (const name of ORDER) {
  const path = resolveClip(name);
  if (!path) continue;
  const card = titleCard(name);
  if (card) clips.push({ name: `${name}∶title`, path: card });
  clips.push({ name, path });
}

if (clips.length === 0) {
  console.error('No clip mp4s found under', CLIPS_DIR);
  process.exit(1);
}

console.log('Composing in order:');
clips.forEach((c, i) => console.log(`  ${i + 1}. ${c.name}  (${c.path.split('/').pop()})`));

// Build the concat-filter graph: normalize each input, then concat.
const inputs: string[] = [];
const norm: string[] = [];
clips.forEach((c, i) => {
  inputs.push('-i', c.path);
  norm.push(
    `[${i}:v]fps=${FPS},scale=${W}:${H}:force_original_aspect_ratio=decrease,` +
      `pad=${W}:${H}:(ow-iw)/2:(oh-ih)/2,setsar=1[v${i}]`,
  );
});
const concatInputs = clips.map((_, i) => `[v${i}]`).join('');
const filter = `${norm.join(';')};${concatInputs}concat=n=${clips.length}:v=1:a=0[out]`;

const outFile = join(SERIES_DIR, 'newsletter-001.mp4');

const args = [
  '-y',
  ...inputs,
  '-filter_complex', filter,
  '-map', '[out]',
  '-c:v', 'libx264',
  '-crf', '18',
  '-preset', 'slow',
  '-pix_fmt', 'yuv420p',
  '-movflags', '+faststart',
  outFile,
];

const res = spawnSync('ffmpeg', args, { stdio: ['ignore', 'inherit', 'inherit'] });
if (res.status !== 0) {
  console.error('ffmpeg concat failed');
  process.exit(1);
}

console.log('\nWrote', outFile);
